services:
  waifulist:
    build: .
    container_name: waifulist
    image: waifulist
    ports:
      - "127.0.0.1:8281:3000"
    volumes:
      - waifulist-data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
      - jikan
    restart: always

  redis:
    image: redis:latest
    container_name: redis_waifulist
    restart: always
    networks:
      default:
        aliases:
          - redis_waifulist
    ports:
      - "127.0.0.1:6339:6379"

  jikan:
    image: jikanme/jikan-rest:latest
    container_name: jikan
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./jikan.env:/app/.env
      - ./jikan-entrypoint.sh:/app/jikan-entrypoint.sh:ro
    depends_on:
      - mongodb_jikan
    entrypoint: ["/app/jikan-entrypoint.sh"]

  mongodb_jikan:
    image: mongo:latest
    container_name: mongodb_jikan
    restart: always
    env_file:
      - jikan.env
    volumes:
      - mongodb_jikan_data:/data/db

volumes:
  waifulist-data:
  mongodb_jikan_data:
